# Generated by Django 2.0.2 on 2018-10-04 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181004_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 21, 6, 48, 69610, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
